# Generated by Django 4.0.5 on 2022-10-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='usn',
            new_name='fk',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Name',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
