# Generated by Django 4.0.5 on 2022-10-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0002_alter_student_managers_rename_usn_attendance_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='current_attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='fk',
        ),
    ]
