# Generated by Django 4.0.5 on 2022-10-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0003_remove_attendance_current_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rana.student'),
            preserve_default=False,
        ),
    ]
