# Generated by Django 4.1 on 2022-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0004_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
