# Generated by Django 4.1 on 2022-10-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0005_school_password_alter_school_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Moderators',
        ),
    ]
