# Generated by Django 4.1 on 2022-10-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0006_rename_school_moderators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderators',
            new_name='Moderator',
        ),
    ]
