# Generated by Django 4.1 on 2022-10-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0009_itslogbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Booking',
        ),
    ]
