# Generated by Django 4.1 on 2022-10-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rana', '0010_rename_appointment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itslogbook',
            name='Name',
            field=models.IntegerField(),
        ),
    ]
